// CODE_CHANGES = getGitChanges()
pipeline {
  
  agent any
  environment {
    //define env variables here
    NEW_VERSION = '1.2.0'
  }
  
  stages {
    
    stage("build") {
      
      steps {
        echo 'building the application...'
        echo "building version ${NEW_VERSION}"
      }
    }
    
    stage("test") {
      // when {
      //   expression {
      //     //boolean expression
      //     CODE_CHANGEs == true
      //   }
      // }
      steps {
        echo 'building the application...'
      }
    }
    
    stage("deploy") {
      
      steps {
        echo 'building the application...'
      }
    }
  }
  post {
    always {
      echo 'pipeline configured'
      //
    }
    failure {
      echo 'pipeline failed'
    
      //
    }
  }
  
}
